spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fastforward
    username: stock
    password: s1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
